import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.SwingConstants;
import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yasir
 */
import java.util.logging.Level;
import java.util.logging.Logger;
public class CalendarRegistration extends javax.swing.JFrame {

    /**
     * Creates new form calendarRegistration
     */
    public CalendarRegistration() {
        initComponents();
        
         this.setLocationRelativeTo(null);// bring the form in the center
    }


/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
                    
                    String fname = jTextField1.getText();
                    String lname = jTextField2.getText();
                    String uname = jTextField3.getText();
                    String pass = String.valueOf(jPasswordField1.getPassword());
                    String re_pass = String.valueOf(jPasswordField2.getPassword());
                    
                     if(uname.equals(""))
                     {
                        JOptionPane.showMessageDialog(null, "Add A Username");
                     }
        
                     else if(pass.equals(""))
                     {
                        JOptionPane.showMessageDialog(null, "Add A Password");
                     }
                     else if(!pass.equals(re_pass))
                     {
                        JOptionPane.showMessageDialog(null, "Retype The Password Again");
                     }
        
                     else if(checkUsername(uname))
                     {
                        JOptionPane.showMessageDialog(null, "This Username Already Exist");
                     }
                     
                     PreparedStatement ps;
                     String query = "INSERT INTO Registration (fname,lname,userid,password) VALUES(?,?,?,?)";
        
                     try {
                            ps = dbconnection.getConnection().prepareStatement(query);
            
                            ps.setString(1, fname);
                            ps.setString(2, lname);
                            ps.setString(3, uname);
                            ps.setString(4, pass);
                            
                            if(ps.executeUpdate() > 0)
                            {
                                JOptionPane.showMessageDialog(null, "New User Add");
                            }
                    }catch (SQLException ex) {
                        Logger.getLogger(CalendarRegistration.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        });
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabelLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new Color(0, 51, 102));

        jLabelExit.setFont(new Font("Berlin Sans FB", Font.PLAIN, 24)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(236, 236, 236));
        jLabelExit.setText("X");
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });

        jLabelMinimize.setFont(new Font("Berlin Sans FB", Font.BOLD, 24)); // NOI18N
        jLabelMinimize.setForeground(new java.awt.Color(236, 236, 236));
        jLabelMinimize.setText("-");
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
        });

        jLabel3.setFont(new Font("Berlin Sans FB", Font.PLAIN, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 236, 236));
        jLabel3.setText("Registration");

        jLabel1.setFont(new Font("Berlin Sans FB", Font.PLAIN, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(210, 215, 211));
        jLabel1.setText("First Name:");

        jLabel2.setFont(new Font("Berlin Sans FB", Font.PLAIN, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(210, 215, 211));
        jLabel2.setText("Last Name:");

        jLabel4.setFont(new Font("Berlin Sans FB", Font.PLAIN, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(210, 215, 211));
        jLabel4.setText("Username:");

        jLabel5.setFont(new Font("Arial", Font.PLAIN, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(210, 215, 211));
        jLabel5.setText("Password:");

        jLabel6.setFont(new Font("Berlin Sans FB", Font.PLAIN, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(210, 215, 211));
        jLabel6.setText("Retype Password:");

        jTextField1.setBackground(new java.awt.Color(108, 122, 137));
        jTextField1.setFont(new Font("Berlin Sans FB", Font.PLAIN, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(210, 215, 211));

        jTextField2.setBackground(new java.awt.Color(108, 122, 137));
        jTextField2.setFont(new Font("Berlin Sans FB", Font.PLAIN, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(210, 215, 211));

        jTextField3.setBackground(new java.awt.Color(108, 122, 137));
        jTextField3.setFont(new Font("Berlin Sans FB", Font.PLAIN, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(210, 215, 211));

        jButton1.setBackground(Color.LIGHT_GRAY);
        jButton1.setFont(new Font("Berlin Sans FB", Font.PLAIN, 20)); // NOI18N
        jButton1.setForeground(new Color(0, 0, 102));
        jButton1.setText("Register");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPasswordField1.setBackground(new java.awt.Color(108, 122, 137));
        jPasswordField1.setFont(new Font("Berlin Sans FB", Font.PLAIN, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(210, 215, 211));

        jPasswordField2.setBackground(new java.awt.Color(108, 122, 137));
        jPasswordField2.setFont(new Font("Berlin Sans FB", Font.PLAIN, 18)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(210, 215, 211));

        jLabelLogin.setFont(new Font("Berlin Sans FB", Font.PLAIN, 16)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(210, 215, 211));
        jLabelLogin.setText("Click here to login!");
        jLabelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(80)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, 441, Short.MAX_VALUE)
        					.addComponent(jLabelMinimize)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jLabelExit)
        					.addContainerGap())
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(27)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabel6)
        						.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(jLabel4)
        							.addComponent(jLabel5))
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(jLabel1)
        								.addComponent(jLabel2))
        							.addGap(1)))
        					.addGap(37)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jTextField2, 140, 140, 140)
        						.addComponent(jTextField1, 139, 139, 139)
        						.addComponent(jTextField3, 140, 140, 140)
        						.addComponent(jPasswordField1, 140, 140, 140)
        						.addComponent(jPasswordField2, 140, 140, 140))
        					.addContainerGap(160, Short.MAX_VALUE))))
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(226, Short.MAX_VALUE)
        			.addComponent(jButton1)
        			.addGap(43)
        			.addComponent(jLabelLogin)
        			.addGap(99))
        		.addGroup(Alignment.LEADING, jPanel2Layout.createSequentialGroup()
        			.addGap(213)
        			.addComponent(jLabel3)
        			.addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabelExit)
        				.addComponent(jLabelMinimize))
        			.addGap(7)
        			.addComponent(jLabel3)
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1))
        			.addGap(44)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2))
        			.addGap(45)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4))
        			.addGap(37)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5))
        			.addGap(36)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jPasswordField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel6))
        			.addGap(42)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabelLogin))
        			.addGap(55))
        );
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jPanel2, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 585, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     public boolean checkUsername(String username)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM Registration WHERE userid =?";
        
        try {
            ps = dbconnection.getConnection().prepareStatement(query);
            ps.setString(1, username);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checkUser = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(CalendarRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
         return checkUser;
    }

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
         System.exit(0);// to clode the REGISTRATION form
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
       this.setState(JFrame.ICONIFIED);//minimize the form
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        
        CalendarLogin log = new CalendarLogin();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalendarRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalendarRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalendarRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalendarRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalendarRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}